/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Kevin
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbHerramienta = new javax.swing.JToolBar();
        btnClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAdmins = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnProductos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVentas = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnReparaciones = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnGarantias = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnFabricantes = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dpVentana = new javax.swing.JDesktopPane();
        mpOpciones = new javax.swing.JMenuBar();
        mAdmins = new javax.swing.JMenu();
        mProductos = new javax.swing.JMenu();
        mVentas = new javax.swing.JMenu();
        mReparaciones = new javax.swing.JMenu();
        mGarantias = new javax.swing.JMenu();
        mFabricantes = new javax.swing.JMenu();
        mClientes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbHerramienta.setBackground(new java.awt.Color(255, 255, 255));
        tbHerramienta.setRollover(true);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_client_management_16px_1.png"))); // NOI18N
        btnClientes.setToolTipText("Mantenimiento de Clientes");
        btnClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClientes.setContentAreaFilled(false);
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnClientes);
        tbHerramienta.add(jSeparator1);

        btnAdmins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_administrator_male_16px.png"))); // NOI18N
        btnAdmins.setToolTipText("Mantenimiento de Administradores");
        btnAdmins.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdmins.setContentAreaFilled(false);
        btnAdmins.setFocusable(false);
        btnAdmins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdmins.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnAdmins);
        tbHerramienta.add(jSeparator2);

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_product_16px.png"))); // NOI18N
        btnProductos.setToolTipText("Mantenimiento de Productos");
        btnProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProductos.setContentAreaFilled(false);
        btnProductos.setFocusable(false);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnProductos);
        tbHerramienta.add(jSeparator3);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_sales_performance_16px_1.png"))); // NOI18N
        btnVentas.setToolTipText("Mantenimiento de Ventas");
        btnVentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVentas.setContentAreaFilled(false);
        btnVentas.setFocusable(false);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnVentas);
        tbHerramienta.add(jSeparator4);

        btnReparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_drill_16px.png"))); // NOI18N
        btnReparaciones.setToolTipText("Mantenimiento de Reparaciones");
        btnReparaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReparaciones.setContentAreaFilled(false);
        btnReparaciones.setFocusable(false);
        btnReparaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReparaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnReparaciones);
        tbHerramienta.add(jSeparator5);

        btnGarantias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_warranty_16px.png"))); // NOI18N
        btnGarantias.setToolTipText("Mantenimiento de Garantias");
        btnGarantias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGarantias.setContentAreaFilled(false);
        btnGarantias.setFocusable(false);
        btnGarantias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGarantias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnGarantias);
        tbHerramienta.add(jSeparator6);

        btnFabricantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_factory_16px.png"))); // NOI18N
        btnFabricantes.setToolTipText("Mantenimiento de Fabricantes");
        btnFabricantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFabricantes.setContentAreaFilled(false);
        btnFabricantes.setFocusable(false);
        btnFabricantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFabricantes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHerramienta.add(btnFabricantes);

        jSplitPane1.setContinuousLayout(true);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SV-DEVICES");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/kelv1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha");

        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("jLabel6");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_exit_64px.png"))); // NOI18N
        btnSalir.setToolTipText("Finalizar Sesion");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Finalizar Sesion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        dpVentana.setBackground(new java.awt.Color(94, 33, 41));

        javax.swing.GroupLayout dpVentanaLayout = new javax.swing.GroupLayout(dpVentana);
        dpVentana.setLayout(dpVentanaLayout);
        dpVentanaLayout.setHorizontalGroup(
            dpVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dpVentanaLayout.setVerticalGroup(
            dpVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(dpVentana);

        mpOpciones.setBackground(new java.awt.Color(94, 33, 41));
        mpOpciones.setForeground(new java.awt.Color(255, 255, 255));

        mAdmins.setForeground(new java.awt.Color(255, 255, 255));
        mAdmins.setText("Administradores");
        mpOpciones.add(mAdmins);

        mProductos.setForeground(new java.awt.Color(255, 255, 255));
        mProductos.setText("Productos");
        mpOpciones.add(mProductos);

        mVentas.setForeground(new java.awt.Color(255, 255, 255));
        mVentas.setText("Ventas");
        mpOpciones.add(mVentas);

        mReparaciones.setForeground(new java.awt.Color(255, 255, 255));
        mReparaciones.setText("Reparaciones");
        mpOpciones.add(mReparaciones);

        mGarantias.setForeground(new java.awt.Color(255, 255, 255));
        mGarantias.setText(" Garantias");
        mpOpciones.add(mGarantias);

        mFabricantes.setForeground(new java.awt.Color(255, 255, 255));
        mFabricantes.setText("Fabricantes");
        mpOpciones.add(mFabricantes);

        mClientes.setForeground(new java.awt.Color(255, 255, 255));
        mClientes.setText("Clientes");
        mpOpciones.add(mClientes);

        setJMenuBar(mpOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblUsuario() {
        return lblUsuario;
    }

    public void setLblUsuario(JLabel lblUsuario) {
        this.lblUsuario = lblUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFabricantes;
    private javax.swing.JButton btnGarantias;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReparaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JDesktopPane dpVentana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu mAdmins;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mFabricantes;
    private javax.swing.JMenu mGarantias;
    private javax.swing.JMenu mProductos;
    private javax.swing.JMenu mReparaciones;
    private javax.swing.JMenu mVentas;
    private javax.swing.JMenuBar mpOpciones;
    private javax.swing.JToolBar tbHerramienta;
    // End of variables declaration//GEN-END:variables
}
